name: "Continuous integration"

on:
  workflow_call:
    inputs:
      plugin-key:
        required: true
        type: string
      glpi-version:
        required: true
        type: string
      php-version:
        required: true
        type: string
      db-image:
        required: true
        type: string
      init-script:
        required: false
        type: string
        default: ""

jobs:
  ci:
    name: "Continuous integration"
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/glpi-project/githubactions-glpi-apache:php-${{ inputs.php-version }}-glpi-${{ inputs.glpi-version }}"
      # `--user github-actions-runner` is mandatory to prevent rights issues on mounted volume during checkout operation
      options: >-
        --volume ${{ github.workspace }}:/var/www/glpi/plugins:rw
        --user github-actions-runner
    services:
      db:
        image: "ghcr.io/glpi-project/githubactions-${{ inputs.db-image }}"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: "glpi"
        options: >-
          --shm-size=1g
    defaults:
      run:
        # By default, execute commands using the `www-data` user to prevent rights issues on GLPI generated files.
        shell: "sudo --set-home --user=www-data bash --noprofile --norc -eo pipefail {0}"
        working-directory: "/var/www/glpi/plugins/${{ inputs.plugin-key }}"
    env:
      CACHE_DIR: "/home/www-data/.cache/continuous-integration-workflow"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          path: "${{ inputs.plugin-key }}"
      - name: "Execute init script"
        if: ${{ inputs.init-script != '' }}
        shell: "bash"
        run: |
          env --ignore-environment bash --noprofile --norc ${{ inputs.init-script }}
      - name: "Configure cache directories"
        # Use default `bash` shell with `github-actions-runner` user
        shell: "bash"
        run: |
          sudo mkdir --parents "${{ env.CACHE_DIR }}/npm"
          sudo mkdir --parents "${{ env.CACHE_DIR }}/composer"
          sudo chown --recursive github-actions-runner "${{ env.CACHE_DIR }}"
          npm config set cache "${{ env.CACHE_DIR }}/npm"
          composer config cache-dir "${{ env.CACHE_DIR }}/composer"
      - name: "Restore cache"
        uses: "actions/cache@v4"
        with:
          path: |
            ${{ env.CACHE_DIR }}
          key: "${{ inputs.plugin-key }}-dependencies-${{ inputs.php-version }}-${{ github.job }}-${{ hashFiles('**/composer.lock', '**/package-lock.json') }}"
          restore-keys: |
            ${{ inputs.plugin-key }}-dependencies-${{ inputs.php-version }}-${{ github.job }}-
            ${{ inputs.plugin-key }}-dependencies-${{ inputs.php-version }}-
            ${{ inputs.plugin-key }}-dependencies-
      - name: "Fix directories ACL"
        # Use default `bash` shell with `github-actions-runner` user
        shell: "bash"
        run: |
          sudo setfacl --recursive --modify u:www-data:rwx "${{ env.CACHE_DIR }}"
          sudo setfacl --recursive --modify u:www-data:rwx /var/www/glpi/plugins
      - name: "Install composer dependencies"
        if: ${{ hashFiles(format('{0}/composer.json', inputs.plugin-key)) != '' }}
        run: |
          composer install --ansi --no-interaction --no-progress --prefer-dist
      - name: "Install npm dependencies"
        if: ${{ hashFiles(format('{0}/package.json', inputs.plugin-key)) != '' }}
        run: |
          npm install --no-save
      - name: "PHP Parallel Lint"
        if: ${{ hashFiles(format('{0}/vendor/bin/parallel-lint', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting PHP Parallel Lint...\033[0m"
          vendor/bin/parallel-lint --colors --exclude ./lib/ --exclude ./node_modules/ --exclude ./vendor/ --no-progress .
      - name: "PHP CodeSniffer"
        if: ${{ hashFiles(format('{0}/vendor/bin/phpcs', inputs.plugin-key)) != '' && hashFiles(format('{0}/.phpcs.xml', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting PHP CodeSniffer...\033[0m"
          vendor/bin/phpcs
      - name: "PHP-CS-Fixer"
        if: ${{ hashFiles(format('{0}/vendor/bin/php-cs-fixer', inputs.plugin-key)) != '' && hashFiles(format('{0}/.php-cs-fixer.php', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting PHP-CS-Fixer...\033[0m"
          PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer check --config=.php-cs-fixer.php --no-interaction --show-progress none
      - name: "PHPStan"
        if: ${{ hashFiles(format('{0}/vendor/bin/phpstan', inputs.plugin-key)) != '' && hashFiles(format('{0}/phpstan.neon', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting PHPStan...\033[0m"
          vendor/bin/phpstan analyze --ansi --memory-limit=2G --no-interaction --no-progress
      - name: "JS Lint"
        if: ${{ hashFiles(format('{0}/node_modules/.bin/eslint', inputs.plugin-key)) != '' && (hashFiles(format('{0}/eslint.config.js', inputs.plugin-key)) != '' || hashFiles(format('{0}/eslint.config.mjs', inputs.plugin-key)) != '' || hashFiles(format('{0}/eslint.config.cjs', inputs.plugin-key)) != '' || hashFiles(format('{0}/.eslintrc.js', inputs.plugin-key)) != '') }}
        run: |
          echo -e "\033[0;33mExecuting ESLint...\033[0m"
          node_modules/.bin/eslint --color .
      - name: "CSS Lint"
        if: ${{ hashFiles(format('{0}/node_modules/.bin/stylelint', inputs.plugin-key)) != '' && hashFiles(format('{0}/.stylelintrc.js', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting Stylelint...\033[0m"
          node_modules/.bin/stylelint --color "**/*.css" "**/*.scss"
      - name: "Misc lint"
        if: ${{ hashFiles(format('{0}/vendor/bin/licence-headers-check', inputs.plugin-key)) != '' && hashFiles(format('{0}/tools/HEADER', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting licence headers checks...\033[0m"
          vendor/bin/licence-headers-check --ansi --no-interaction
      - name: "Install plugin"
        working-directory: "/var/www/glpi"
        run: |
          bin/console database:install --ansi --no-interaction --db-name=glpi --db-host=db --db-user=root --db-password="" --strict-configuration
          php bin/console config:set url_base "http://localhost"
          php bin/console config:set url_base_api "http://localhost/apirest.php"
          bin/console plugin:install --ansi --no-interaction --username=glpi ${{ inputs.plugin-key }}
          bin/console plugin:activate --ansi --no-interaction ${{ inputs.plugin-key }}
      - name: "Run apache"
        # Use default `bash` shell with `github-actions-runner` user
        shell: "bash"
        run: |
          sudo service apache2 start
      - name: "PHPUnit"
        if: ${{ hashFiles(format('{0}/vendor/bin/phpunit', inputs.plugin-key)) != '' && hashFiles(format('{0}/phpunit.xml', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting PHPUnit...\033[0m"
          php vendor/bin/phpunit --colors=always
      - name: "Jest"
        if: ${{ hashFiles(format('{0}/node_modules/.bin/jest', inputs.plugin-key)) != '' && hashFiles(format('{0}/jest.config.js', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting Jest...\033[0m"
          NODE_OPTIONS="--experimental-vm-modules" node_modules/.bin/jest --colors --forceExit
      - name: "TwigCS"
        if: ${{ hashFiles(format('{0}/vendor/bin/twigcs', inputs.plugin-key)) != '' && hashFiles(format('{0}/.twig_cs.dist.php', inputs.plugin-key)) != '' }}
        run: |
          echo -e "\033[0;33mExecuting TwigCS...\033[0m"
          vendor/bin/twigcs
